collections:
  - name: ansible.windows
    source: https://old-galaxy.ansible.com/
  - name: community.windows
    source: https://old-galaxy.ansible.com/
  - name: community.general
    source: https://old-galaxy.ansible.com/
  - name: community.vmware
    source: https://old-galaxy.ansible.com/
  - name: ansible.windows
    source: https://old-galaxy.ansible.com/
  - name: vmware.vmware_rest